# Generated by Django 5.2.2 on 2025-12-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='bonus_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
